/* 상품 소분류 */
SELECT * FROM SMALL_CTGR;

CREATE TABLE SMALL_CTGR (
	SMALL_CTGR_ID NUMBER NOT NULL, /* 상품 소분류 ID */
	SMALL_CTGR_NAME VARCHAR2(100), /* 상품 소분류 명 */
	MEDIUM_CTGR_ID NUMBER /* 상품 중분류 ID */
);
create sequence seq_SMALL_CTGR;
/*여성의류*/ 
--상의
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '반소매 티셔츠', 11 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '긴소매 티셔츠', 11 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '슬리브리스', 11 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '스웨트셔츠', 11 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '후디', 11 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '셔츠', 11 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '블라우스', 11 );
--바지
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '부츠컷', 12 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '쇼트', 12 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '슬림', 12 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '스트레이트', 12 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '와이드', 12 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '데님', 12 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '트레이닝', 12 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '레깅스', 12 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '슬랙스', 12 );
--원피스
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '미니 원피스', 13 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '미디 원피스', 13 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '롱 원피스', 13 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '데님 원피스', 13 );
--스커트
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '미니', 14 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '미디', 14 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '롱', 14 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '데님', 14 );
--셋업
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '수트', 15 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '스웻', 15 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '트레이닝', 15 );
--액티브웨어
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '상의', 17 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '하의', 17 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '원피스,모노키니', 17 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '비키니', 17 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '래쉬가드', 17 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '커버업', 17 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '스윔웨어 액세서리', 17 );
--아우터
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '무스탕', 18 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '바람막이', 18 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '레더 재킷', 18 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '재킷', 18 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '퍼재킷', 18 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '나일론 재킷', 18 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '트레이닝 재킷', 18 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '데님 재킷', 18 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '후드 집업', 18 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '아노락', 18 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '점퍼', 18 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '플리스', 18 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '하프코트', 18 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '숏코트', 18 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '롱코트', 18 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '트렌치 코트', 18 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '롱패딩', 18 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '경량패딩', 18 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '숏패딩', 18 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '베스트', 18 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '로브', 18 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '블루종', 18 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '야상', 18 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '바시티', 18 );
--니트웨어
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '브이넥', 19 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '크루넥', 19 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '터틀넥', 19 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '카디건', 19 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '베스트', 19 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '캐시미어', 19 );
--이너웨어
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '브라', 110 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '팬티', 110 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '세트', 110 );
--홈웨어
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '원피스', 111 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '상의', 111 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '하의', 111 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '세트', 111 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '로브', 111 );
--해외브랜드
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '아우터', 112 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '상의', 112 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '하의', 112 );
/*여성신발*/
--플랫,로퍼
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '플랫', 123 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '로퍼', 123 );
--부츠
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '앵클 부츠', 124 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '니하이 부츠', 124 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '플랫 부츠', 124 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '미드힐 부츠', 124 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '하이힐', 124 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '레인 부츠', 124 );
--샌들
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '플랫', 125 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '힐', 125 );
--펌프스
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '미드힐', 126 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '하이힐', 126 );
--슬리퍼,뮬
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '슬리퍼', 127 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '뮬', 127 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '플립플랍', 127 );
--스니커즈
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '하이탑', 128 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '로우탑', 128 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '슬립온', 128 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '러닝화', 128 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '기능성 운동화', 128 );
/*여성액세서리*/
--지갑,카드케이스
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '카드케이스', 131 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '지갑', 131 );
--주얼리
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '14K골드', 132 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '귀걸이', 132 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '진주귀걸이', 132 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '목걸이', 132 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '진주목걸이', 132 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '반지', 132 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '팔찌', 132 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '발찌', 132 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '브로치,펜던트', 132 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '주얼리세트', 132 );
--모자
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '버킷햇', 133 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '바라클라바', 133 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '베레모', 133 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '볼캡', 133 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '비니', 133 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '페도라', 133 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '트루퍼', 133 );
--시계
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '가죽시계', 134 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '메탈시계', 134 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '패브릭시계', 134 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '우드시계', 134 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '전자,스포츠시계', 134 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '시계 액세서리', 134 );
--아이웨어
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '안경', 135 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '선글라스', 135 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '안대', 135 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '아이웨어 액세서리', 135 );
--양말
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '양말', 137 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '페이크,발목양말', 137 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '니삭스,레그워머', 137 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '스타킹', 137 );
--헤어액세서리
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '귀마개', 142 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '두건,반다나', 142 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '머리띠,밴드', 142 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '머리끈', 142 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '헤어핀', 142 );
--기타액세서리
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '키링', 143 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '손수건', 143 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '마스크', 143 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '우산', 143 );
/*남성의류*/
--해외브랜드
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '아우터', 21 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '상의', 21 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '하의', 21 );
--아우터
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '무스탕', 22 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '플리스', 22 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '야상', 22 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '블루종', 22 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '바시티', 22 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '데님 재킷', 22 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '퍼 재킷', 22 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '트레이닝  재킷', 22 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '점퍼', 22 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '바람막이', 22 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '아노락', 22 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '트렌치, 맥코트', 22 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '나일론, 코치 재킷', 22 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '후드 집업', 22 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '베스트', 22 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '레더 재킷', 22 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '블레이저', 22 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '롱코트', 22 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '숏코트', 22 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '하프코트', 22 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '경량패딩', 22 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '숏패딩', 22 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '롱패딩', 22 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '기타 아우터', 22 );
--상의
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '반소매 셔츠', 23 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '반소매 티셔츠', 23 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '피케,카라 티셔츠', 23 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '슬리브리스', 23 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '스웨트셔츠', 23 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '후디', 23 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '집업', 23 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '긴소매 티셔츠', 23 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '긴소매 셔츠', 23 );
--하의
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '레깅스', 24 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '쇼트', 24 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '부츠컷', 24 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '슬림 팬츠', 24 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '스트레이트 팬츠', 24 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '와이드 팬츠', 24 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '데님 팬츠', 24 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '트레이닝 팬츠', 24 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '슬랙스', 24 );
--홈웨어
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '상의', 25 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '하의', 25 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '세트', 25 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '로브', 25 );
--셋업
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '수트', 26 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '스웻', 26 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '트레이닝', 26 );
--이너웨어
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '팬티', 27 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '언더셔츠', 27 );
--니트웨어
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '터틀넥', 28 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '브이넥', 28 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '크루넥', 28 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '폴로 셔츠', 28 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '카디건', 28 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '베스트', 28 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '집업', 28 );
/*남성신발*/
--스니커즈
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '하이탑', 222 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '로우탑', 222 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '슬립온', 222 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '러닝화', 222 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '기능성 운동화', 222 );
--로퍼
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '페니로퍼', 223 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '플레인로퍼', 223 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '태슬 로퍼', 223 );
--구두
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '더비', 224 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '레이스업', 224 );
--부츠
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '첼시 부츠', 225 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '데저트 부츠', 225 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '미들 부츠', 225 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '레인 부츠', 225 );
--샌들
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '슬리퍼', 226 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '플립플랍', 226 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '뮬', 226 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '샌들', 226 );
/*남성액세서리*/
--지갑,카드케이스
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '지갑', 228 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '카드케이스', 228 );
--아이웨어
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '안경', 230 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '선글라스', 230 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '아이웨어 액세서리', 230 );
--시계
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '가죽시계', 231 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '메탈시계', 231 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '패브릭시계', 231 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '우드시계', 231 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '전자,스포츠시계', 231 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '시계 액세서리', 231 );
--모자
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '버킷햇', 232 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '바라클라바', 232 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '베레모', 232 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '볼캡', 232 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '비니', 232 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '페도라', 232 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '트루퍼', 232 );
--벨트
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '벨트', 234 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '서스펜더', 234 );
--양말
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '양말', 235 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '페이크,발목양말', 235 );
--주얼리
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '귀걸이', 240 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '목걸이', 240 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '반지', 240 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '팔찌', 240 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '발찌', 240 );
--기타 액세서리
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '키링', 241 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '손수건', 241 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '마스크', 241 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '우산', 241 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '헤드밴드', 241 );
/*가구-비앤비이탈리아*/
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '좌식 테이블', 31 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '의자', 31 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '협탁,미니 테이블', 31 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '소파', 31 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '식탁', 31 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '스툴,벤치', 31 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '암체어', 31 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '아웃도어', 31 );
--침구
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '침구세트', 32 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '차렵이불', 32 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '솜,구스이불', 32 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '홑이불', 32 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '이불솜', 32 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '이불커버', 32 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '토퍼', 32 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '매트리스커버', 32 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '스프레드', 32 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '쿠션', 32 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '베개', 32 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '베개커버', 32 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '쿠션커버', 32 );
--홈패브릭
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '커튼', 33 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '커튼 부자재', 33 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '블라인드', 33 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '러그', 33 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '방석', 33 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '실내화', 33 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '앞치마', 33 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '담요', 33 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '소파커버', 33 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '소파패드', 33 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '티슈커버', 33 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '기타커버', 33 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '장바구니', 33 );
--가구
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '침대', 34 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '매트리스', 34 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '옷장', 34 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '협탁,미니테이블', 34 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '좌식 테이블', 34 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '식탁', 34 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '주방수납,선반', 34 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '화장대', 34 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '수납장,서랍장', 34 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '책장', 34 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '소파', 34 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '의자', 34 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '스툴,벤치', 34 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '책상', 34 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '오피스의자', 34 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '접이식의자,캠핑체어', 34 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '아웃도어가구', 34 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '라운지체어', 34 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '행거', 34 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '거실장', 34 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '선반', 34 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '트롤리', 34 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '변선반', 34 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '가벽,파티션', 34 );
--조명
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '벽조명', 35 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '포터블 조명', 35 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '장식등', 35 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '무드등', 35 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '팬던트조명', 35 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '장스탠드', 35 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '단스탠드', 35 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '데스크스탠드 ', 35 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '기타조명', 35 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '부속품', 35 );
--홈데코
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '거울', 36 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '벽시계', 36 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '시계', 36 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '행잉데코,모빌', 36 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '월데코', 36 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '포스터', 36 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '액자', 36 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '우드소품', 36 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '인테리어소품', 36 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , 'DIY', 36 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '오브제', 36 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '인형', 36 );
--가드닝
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '씨앗', 37 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '조화', 37 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '식물,꽃', 37 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '화병', 37 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '화분', 37 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '화분커버', 37 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '식물 영양제', 37 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '토분', 37 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '물조리개', 37 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '가드닝용품', 37 );
--홈프레그런스
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '인센스', 38 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '캔들', 38 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '디퓨저', 38 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '룸스프레이', 38 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '아로마,에센셜 오일', 38 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '홀더,트레이', 38 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '점화도구', 38 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '프레그런스 액세서리', 38 );
--아트,디자인
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '오리지널,에디션', 39 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '아트프린트', 39 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '오브제,공예품', 39 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '예술,디자인 서적', 39 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '굿즈', 39 );
--책,음반
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '도서', 310 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '음반', 310 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '매거진', 310 );
--스테이셔너리
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '북 악세서리', 311 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '캘린더', 311 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '다이어리,플래너', 311 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '테이프', 311 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '스티커', 311 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '필기류,미술용품', 311 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '노트,메모', 311 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '카드,엽서', 311 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '기타 문구용품', 311 );
/*주방,생활*/
--청소,수납
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '신발정리', 41 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '우산꽂이', 41 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '화장대정리', 41 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '빨래용품', 41 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '섬유 향수,탈취제', 41 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '세탁세제', 41 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '안전용품', 41 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '화장지', 41 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '청소용품', 41 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '옷걸이', 41 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '식기건조대', 41 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '기타주방수납', 41 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '주방세제', 41 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '싱크대용품', 41 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '청소세제', 41 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '행주', 41 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '수세미', 41 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '리빙박스,바스켓', 41 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '휴지통,분리수거함', 41 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '탈취,제습제', 41 );
--쿡웨어
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '스텐프라이팬', 42 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '주물프라이팬', 42 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '그릴', 42 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '스낵메이커', 42 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '칼', 42 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '도마', 42 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '가위', 42 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '채반', 42 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '휴대용버너', 42 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '저장용기', 42 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '스텐 키친툴', 42 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '믹싱볼', 42 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '우드 키친툴', 42 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '1구 인덕션', 42 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '실리콘 키친툴', 42 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '기타 키친툴', 42 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '스텐냄비', 42 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '주물냄비', 42 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '뚝배기', 42 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '세라믹냄비', 42 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '기타냄비', 42 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '프라이팬', 42 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '주전자', 42 );
--테이블웨어
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '커피웨어', 43 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '커트러리', 43 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '와인잔', 43 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '고블렛', 43 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '와인 악세서리', 43 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '기타주류잔', 43 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '티팟', 43 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '물병', 43 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '볼', 43 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '트레이', 43 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '수저보관함', 43 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '티웨어', 43 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '티코스터', 43 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '테이블매트', 43 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '테이블커버', 43 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '테이블 소품', 43 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '찬기', 43 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '종지,미니볼', 43 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '공기,국기', 43 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '면기', 43 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '숟가락,젓가락', 43 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '식기세트', 43 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '플레이트', 43 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '머그컵', 43 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '유리컵', 43 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '텀블러', 43 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '커피잔,찻잔', 43 );
--욕실
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '가글', 44 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '치약', 44 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '페이스타월', 44 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '핸드타월', 44 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '비치타월', 44 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '칫솔', 44 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '욕실용품', 44 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '샤워용품', 44 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '발매트', 44 );
--반려동물
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '쿠션,침대', 45 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '의류', 45 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '하우스', 45 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '강아지 음식', 45 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '고양이 음식', 45 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '강아지 용품', 45 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '고양이 용품', 45 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '강아지 장난감', 45 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '고양이 장난감', 45 );
/*가전*/
--영상가전
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , 'TV', 51 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '모니터', 51 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '프로젝터', 51 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '사운드바', 51 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '기타 액세서리', 51 );
--주방가전
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '일반냉장고,냉동고', 52 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '양문형냉장고', 52 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '김치냉장고,와인셀러', 52 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '전기주전자', 52 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '에어프라이어', 52 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '토스터,홈베이킹', 52 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '쿠커,그릴', 52 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '블랜더,믹서', 52 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '오븐,전자레인지', 52 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '가스레인지,인덕션', 52 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '전기밥솥', 52 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '식기세척기,세제', 52 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '커피머신', 52 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '기타주방가전', 52 );
--세탁기,건조기
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '드럼세탁기', 53 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '일반세탁기', 53 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '건조기', 53 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '의류관리기', 53 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '미니세탁기,건조기', 53 );
--청소기
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '무선청소기', 54 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '로봇청소기', 54 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '물걸레청소기', 54 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '스팀청소기', 54 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '유선청소기', 54 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '차량용,핸디청소기', 54 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '침구청소기', 54 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '액세서리', 54 );
--생활가전
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '미싱,다리미', 55 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '멀티탭', 55 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '보풀제거기', 55 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '기타 생활가전', 55 );
--계절가전
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '공기청정기', 56 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '선풍기,냉풍기', 56 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '제습기', 56 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '에어컨', 56 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '가습기', 56 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '온열매트,온수매트', 56 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '전기히터,온풍기', 56 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '기타 계절가전', 56 );
--이미용가전
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '드라이기', 57 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '고데기,매직기', 57 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '면도기,제모기', 57 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '전동칫솔,칫솔살균기', 57 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '기타 이미용가전', 57 );
--건강가전
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '안마의자', 58 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '안마기', 58 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '기타 건강가전', 58 );
--리퍼브
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '리퍼브', 59 );
/*컴퓨터,디지털*/
--음향기기
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '이어폰', 61 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '헤드폰', 61 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '스피커', 61 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '마이크', 61 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '턴테이블', 61 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '사운드바', 61 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '오디오 액세서리', 61 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '이어폰,헤드폰 케이스', 61 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '이어폰,헤드폰 액세서리', 61 );
--모바일,웨어러블
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '핸드폰,스마트폰', 62 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '태블릿', 62 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '스마트워치', 62 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '보조배터리', 62 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '케이블,젠더', 62 );
--모바일 액세서리
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '스마트폰 케이스', 63 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '그립톡', 63 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '태블릿 액세서리', 63 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '스마트워치 액세서리', 63 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '이어폰,헤드폰 액세서리', 63 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '충전기,거치대', 63 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '보호필름', 63 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '기타 액세서리', 63 );
--PC,노트북
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '데스크탑', 64 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '노트북', 64 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '프린터 및 주변기기', 64 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , 'PC,노트북 액세서리', 64 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '저장장치', 64 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '모니터', 64 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '키보드', 64 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '마우스', 64 );
--게임
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '게임기', 65 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '타이틀', 65 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '액세서리', 65 );
--사진
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '카메라', 66 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '렌즈', 66 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '가방,파우치', 66 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '삼각대', 66 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '필름', 66 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '메모리카드', 66 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '인화용품', 66 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '스트랩', 66 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '기타 액세서리', 66 );
--자동차용품,장난감
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '차량용 공기청정기', 67 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '방향제', 67 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '충전,거치대', 67 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '기타 자동차 액세서리', 67 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '아트토이', 67 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '보드게임', 67 );
--스마트모빌리티
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '전기자전거', 68 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '전동스쿠터', 68 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '모빌리티 액세서리', 68 );
/*뷰티*/
--스킨케어
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '미백,톤업', 72 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '립밤,립케어', 72 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '스킨,토너', 72 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '미스트', 72 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '에센스,세럼,앰플', 72 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '오일', 72 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '로션,에멀전', 72 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '크림', 72 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '아이,넥 케어', 72 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '선케어', 72 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '마스크, 팩', 72 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '클렌징', 72 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '페이셜 패드', 72 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '스킨케어세트 ', 72 );
--바디케어
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '손소독제,핸드워시', 76 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '바디워시', 76 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '스크럽', 76 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '로션,크림', 76 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '바디오일', 76 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '데오드란트', 76 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '제모,왁싱', 76 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '핸드크림', 76 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '풋케어', 76 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '비누', 76 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '입욕제,소금', 76 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '바디케어세트', 76 );
--헤어케어
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '샴푸', 77 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '린스,컨디셔너', 77 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '탈모케어', 77 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '트리트먼트,헤어팩', 77 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '헤어에센스,헤어오일', 77 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '헤어미스트', 77 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '헤어케어세트', 77 );
--메이크업
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '베이스,프라이머', 78 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '컨실러', 78 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '하이라이터', 78 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '블러셔', 78 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '파우더,파우더팩트', 78 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '립스틱,립틴트', 78 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '아이섀도우', 78 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '아이라이너,마스카라', 78 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '메이크업도구', 78 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '메이크업세트', 78 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '쿠션,팩트', 78 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '파운데이션, BB, CC', 78 );
--네일, 디자인타투
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '네일,패디', 79 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '네일기기,도구', 79 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '타투', 79 );
--향수
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '남성향수', 710 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '니치향수', 710 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '여성향수', 710 );
--여성용품
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '생리대', 711 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '생리컵,탐폰', 711 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '청결제', 711 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '건강의료용품', 711 );
--뷰티기기, 마스크
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '화장솜,면봉', 712 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '기타뷰티소품', 712 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '스킨케어기기', 712 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '바디케어기기', 712 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '건강마스크', 712 );
--남성뷰티
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '스킨케어', 713 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '면도제품', 713 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '클렌저', 713 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '맨바디,헤어케어', 713 );
--스킨타입
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '건조', 714 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '민감성', 714 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '지성,트러블', 714 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '손상', 714 );
--이너뷰티
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '가벼운간식', 715 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '면역력증진', 715 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '철저한 식단관리', 715 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '튼튼함을 위한 식품', 715 );
/*푸드*/
--선물세트
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '유음료', 81 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '꿀,잼,오일', 81 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '건강', 81 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '간식', 81 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '이너뷰티', 81 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '신선', 81 );
--음료
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '커피', 82 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '차', 82 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '전통주', 82 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '음료,쥬스,즙', 82 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '물,탄산수', 82 );
--가공식품
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '잼,꿀', 83 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '유제품', 83 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '반조리식품', 83 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '쿠킹박스', 83 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '스낵', 83 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '베이커리,떡', 83 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '견과류,건과일', 83 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '초콜렛,사탕', 83 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '면,파스타', 83 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '소스', 83 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '오일', 83 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '냉동식품', 83 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '홍삼류', 83 );
--신선,냉장
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '육류,계란', 84 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '수산,해산물', 84 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '과일,채소', 84 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '국,반찬', 84 );
/*레저*/
--캠핑
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '아이스박스', 91 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '랜턴', 91 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '조명', 91 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '쿨러', 91 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '텀블러', 91 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '텐트,타프,쉘터', 91 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '퍼니처', 91 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '침낭,매트,해먹', 91 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '스토브,화로대', 91 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '키친', 91 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '기타용품 ', 91 );
--등산,하이킹
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '아우터', 92 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '상의', 92 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '하의', 92 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '신발', 92 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '가방', 92 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '장비,용품', 92 );
--골프
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '클럽', 93 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '아우터', 93 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '상의', 93 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '하의', 93 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '신발', 93 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '가방', 93 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '잡화', 93 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '장비,용품', 93 );
--수영
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '여성 수영복', 94 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '여성 비키니', 94 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '남성 수영복', 94 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '래쉬가드', 94 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '스윔웨어 액세서리', 94 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '용품', 94 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '서핑', 94 );
--러닝
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '상의', 95 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '하의', 95 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '신발', 95 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '장비,용품', 95 );
--실내운동
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '상의', 96 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '하의', 96 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '장비,용품', 96 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '가구', 96 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '커버업', 96 );
--여행
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '캐리어', 97 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '여행가방', 97 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '여행소품', 97 );
--테니스
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '상의', 98 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '하의', 98 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '신발', 98 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '가방', 98 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '잡화', 98 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '장비,용품', 98 );
--자전거
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '자전거', 99 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '장비,용품', 99 );
/*유아,아동*/
--의류
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '상의', 101 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '하의', 101 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '원피스', 101 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '스커트', 101 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '반바지', 101 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '스웨터,니트', 101 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '실내복', 101 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '속옷', 101 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '양말,레그웨어', 101 );
--신발,가방
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '운동화', 102 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '샌들', 102 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '장화', 102 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '가방', 102 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '잡화', 102 );
--아동,홈
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '테이블웨어', 103 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '침구,패브릭', 103 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '욕실', 103 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '장난감', 103 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '유아용품', 103 );
/*컬처*/
--티켓
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '전시,행사', 1101 );
INSERT INTO SMALL_CTGR(SMALL_CTGR_ID, SMALL_CTGR_NAME, MEDIUM_CTGR_ID) VALUES (seq_SMALL_CTGR.nextval , '클래스,멤버십,이용권', 1101 );


/* 상품 중분류 */
SELECT * FROM MEDIUM_CTGR;


